### ISSUE TITLE
AMLEditor.exe deleted on click, installation fails

### ISSUE THREAD

**Issue by DaEwe** [AutomationML/AutomationMLEditor#14]
Steps to reproduce:
1 - Download latest release zip
2 - Unzip folder
3 - Doubleclick "AMLEditor.exe"

Result:
1. Error Message "Windows cannot find 'C:\Users\XXX\Downloads\AML.Editor_6.2.7\AMLEditor.exe'. Make sure you typed the name correctly, and then try again."
2. AMLEditor.exe has disappeared from folder

System: Microsoft Windows 10 Enterprise
Version: 10.0.19045 Build 19045
System Type: x64-based PC

**Comment by josefprinz** [comment]
I tried to reproduce the behaviour but could not find any errors. Latest release is 6.2.8. Download it from this side: https://github.com/AutomationML/AutomationMLEditor/releases/tag/v6.2.8. The .exe file should not be removed to another folder after unzip. For a clean environment try to delete the AutomationML roaming folder if it exists in %AppData%. First time users will get a window warning message when starting the exe, warning for an unknown provider (ignore this). The executable is not signed.

**Comment by josefprinz** [comment]
![grafik](https://github.com/user-attachments/assets/cf831cd8-5b1d-4878-bd08-d53aa5c89a1b)

File properties of the executable show the secutity warning. Mark the check box.
