### ISSUE TITLE
Editor crashes on startup if config file setting ResolveExternalReferences is set to True

### ISSUE THREAD

**Issue by JimLuth** [AutomationML/AutomationMLEditor#3]
Editor crashes on startup if config file setting ResolveExternalReferences is set to True.

Set the option on as shown in the first screen shot and close the Editor.
![checkbox](https://user-images.githubusercontent.com/6538603/141523146-75e2922d-d4c0-4ec7-9981-fd5b32d7f765.png)

Restart the Editor and observe the crash in the second screen shot.
![Error](https://user-images.githubusercontent.com/6538603/141523204-29baf82b-9c6f-4e17-80d9-89b06e4314fe.png)

**Comment by AutomationML** [comment]
this is fixed in version 5.6.9
