### ISSUE TITLE
v6.1.0 can't find .net

### ISSUE THREAD

**Issue by NPKBender** [AutomationML/AutomationMLEditor#7]
Expected: Installing AutomationMLEditor works with v6.x.x of Microsoft .NET framework.
Actual: AMLEditor doesn't work with v6.0.8 of .NET framework. Additionally, rolling back to v6.0.0 still does not satisfy the program, which displays a message about being unable to locate the .NET program.

As a side note, the linked release on the AutomationML webpage is for v6.0.4, which has a nasty known bug (#4). Might want to update that link.

Solution: Install version 5.6.

**Comment by josefprinz** [comment]
I cheked it using v6.0.8 and there are no problems using Editor version  6.1.

**Comment by josefprinz** [comment]
dotnet sdk check should show:

Microsoft.NETCore.App             6.0.8        Auf dem neuesten Stand.
Microsoft.WindowsDesktop.App      6.0.8        Auf dem neuesten Stand.
