### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by jcos1** [AutomationML/AutomationMLEditor#8]
Actually 2 issues:

1.
The installer (download link on the automationml website) does not work.
It puts all files directly under c:\ no matter which path I select.
Nothing happens when running this installed executable.

2.
The github zip file works, but a pop-up appears to download .net runtime.
But this then downloads the wrong runtime.
It should download the desktop runtime instead.

**Comment by josefprinz** [comment]
should work with version 6.1.1
