### ISSUE TITLE
Error on Startup "Plugin instantiation failed" (V 5.6.10)

### ISSUE THREAD

**Issue by DamnDaniel-98** [AutomationML/AutomationMLEditor#9]
I have downgraded from an newer version to an older one (to V 5.6.10)
When starting up the AMLEditor following errormessage occurs
![grafik](https://user-images.githubusercontent.com/61795864/231253727-d0c28d5a-dd5c-4c4d-b24a-34c8da3620bf.png)
And i am not able to install any plugins. When i click on install, the programm says it was successfull, but  in the plugin-menu in the toolbar no plugin appears. 
I have already tried to reinstall the software.

**Comment by DamnDaniel-98** [comment]
Now I have the problem on my second PC as well. When I open the program from the start menu icon, an administrator message came up that seemed like the software was being updated. I pressed "Yes." The program opened and has since behaved as described above.

**Comment by josefprinz** [comment]
The AutomationML Editor until Version 5.10 loads plugins from %AppData%/AutomationMLEditor/Plugins, if there are problems loading plugins after a downgrade or reinstallation it is recommended to delete the Plugins folder as well as the Plugins6 folder used for the version 6 of the editor. Version 5.10 should be unistalled and reinstalled. The reinstallation will create a fresh plugins folder with standard plugins. If there will be still any problems please examine the log file an publish the latest content of that file.

**Comment by josefprinz** [comment]
Please note that v6 plugins cannot be used with v5.

**Comment by DamnDaniel-98** [comment]
After deleting the plugin folder (%AppData%\Roaming\AutomationMLEditor\PlugIns), at least the error message no longer appeared on startup. However, the plugin "Aml.Editor.Plugin.AMLDraw" cannot be installed. The error image remains the same (plugin seems to be installed successfully, but does not appear in the toolbar). Reinstallation has been tried several times.

**Comment by DamnDaniel-98** [comment]
[ErrorLog.txt](https://github.com/AutomationML/AutomationMLEditor/files/11215390/ErrorLog.txt)
Enclosed the log file.

**Comment by josefprinz** [comment]
For version 5 of the editor the aml.draw plugin requires [version 1.3.4](https://www.nuget.org/api/v2/package/Aml.Editor.Plugin.AMLDraw/1.3.4).

It is not possible to use the plugin manager of editor version 5 to load plugins which are updated to be used with .net 6 and the editor version 6. You can try to download the correct plugin version and install it manually by unzipping the nuget file and copying the dlls to the plugin folder.

Because AutomationML does not offer any support for version 5 of the editor, this cannot be changed.
